#!/usr/bin/env python3
"""
make_sample.py -- generate sample toolpaths so the repo runs before you have
your own files. Produces a twisted-hex vase in FDM G-code and a short KUKA KRL
program that traces a helix, letting you exercise both parser paths.

    python3 make_sample.py --outdir ../samples
"""

import argparse
import math
from pathlib import Path


def twisted_vase(path, layers=180, layer_h=0.3, sides=6, radius=28.0,
                 twist_deg=220.0, taper=0.55, seg_per_side=14):
    """Spiral-vase style single-wall print. ~60k moves, realistic file size."""
    lines = [
        "; generated by make_sample.py -- twisted hex vase",
        "; a synthetic but structurally realistic slicer output",
        "M82", "G21", "G90", "G28",
        "M104 S210", "M109 S210", "M140 S60",
        "G92 E0",
    ]
    e = 0.0
    flow = 0.041  # mm of filament per mm of travel, roughly 0.4 nozzle / 0.3 layer

    px = py = None
    for li in range(layers):
        t = li / max(layers - 1, 1)
        z = round((li + 1) * layer_h, 3)
        r = radius * (1.0 - taper * (t ** 1.6))
        phase = math.radians(twist_deg) * t

        lines.append(f";LAYER:{li}")
        lines.append(f";Z:{z}")

        pts = []
        total = sides * seg_per_side
        for s in range(total + 1):
            a = 2 * math.pi * s / total + phase
            # Rounded-corner polygon: blend a circle with an n-gon.
            k = math.cos(math.pi / sides) / math.cos(
                ((a * sides) % (2 * math.pi)) / sides - math.pi / sides)
            rr = r * (0.72 + 0.28 * k)
            pts.append((100 + rr * math.cos(a), 100 + rr * math.sin(a)))

        if li == 0:
            lines.append(f"G0 F4200 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} Z{z}")
            px, py = pts[0]
        else:
            lines.append(f"G1 F1500 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} Z{z} E{e:.5f}")

        for (x, y) in pts[1:]:
            d = math.hypot(x - px, y - py)
            e += d * flow
            lines.append(f"G1 X{x:.3f} Y{y:.3f} E{e:.5f}")
            px, py = x, y

    lines += ["M104 S0", "M140 S0", "G28 X0 Y0", "M84"]
    Path(path).write_text("\n".join(lines) + "\n")
    return len(lines)


def helix_krl(path, turns=14, pts_per_turn=48, radius=180.0, rise=9.0):
    """KUKA KRL program: approach, trace a rising helix with the tool on, retract."""
    lines = [
        "DEF helix_demo()",
        "; generated by make_sample.py -- robot arm sample",
        "  BAS(#INITMOV,0)",
        "  $VEL.CP = 0.4",
        "  PTP {X 0, Y 0, Z 400}",
        f"  PTP {{X {radius:.2f}, Y 0.00, Z 20.00}}",
        "  ExtrudeOn()",
    ]
    for i in range(turns * pts_per_turn + 1):
        a = 2 * math.pi * i / pts_per_turn
        z = 20.0 + rise * (i / pts_per_turn)
        rr = radius * (1.0 - 0.35 * (i / (turns * pts_per_turn)))
        x = rr * math.cos(a)
        y = rr * math.sin(a)
        lines.append(f"  LIN {{X {x:.2f}, Y {y:.2f}, Z {z:.2f}}} C_DIS")
    lines += [
        "  ExtrudeOff()",
        "  PTP {X 0, Y 0, Z 400}",
        "END",
    ]
    Path(path).write_text("\n".join(lines) + "\n")
    return len(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="../samples")
    args = ap.parse_args()

    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)

    g = out / "twisted_vase.gcode"
    k = out / "helix_arm.src"

    n1 = twisted_vase(g)
    n2 = helix_krl(k)

    print(f"{g}  ({n1:,} lines, {g.stat().st_size/1024:.0f} KB)")
    print(f"{k}  ({n2:,} lines, {k.stat().st_size/1024:.0f} KB)")


if __name__ == "__main__":
    main()
